#!/bin/bash

readonly MYADM_DIR="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd
)"
readonly MYADM_COMMON_PKGS=("fzf" "ripgrep" "unrar")
readonly MYADM_VIM_PLUGIN_DIR="${HOME}"/.vim/pack/dist/start
readonly MYADM_COMMON_VIM_PLUGINS=(
  "https://github.com/vim-airline/vim-airline.git"
  "https://github.com/junegunn/fzf.vim"
)

MYADM_PKGS_TO_INSTALL=()

install_vim_plugins() {
  plugins=("$@")

  [[ ! -d "${MYADM_VIM_PLUGIN_DIR}" ]] && mkdir -p "${MYADM_VIM_PLUGIN_DIR}"

  for plugin in "${plugins[@]}"; do
    local reponame="${plugin##*/}"
    local install_path="${MYADM_VIM_PLUGIN_DIR}"/"${reponame%.*}"

    if [[ ! -d "${install_path}" ]]; then
      git clone "${plugin}" "${install_path}"
    fi
  done
}


bootstrap() {
  myadm_pkg_mgr_prep
  myadm_check_installed_pkgs "${MYADM_COMMON_PKGS[@]}" "${MYADM_OS_PKGS[@]}"

  if [[ "${#MYADM_PKGS_TO_INSTALL[@]}" -ne 0 ]]; then
    "${MYADM_INSTALL_CMD[@]}" "${MYADM_PKGS_TO_INSTALL[@]}"
  else
    yellow_echo "No packages to install"
  fi

  install_vim_plugins \
    "${MYADM_COMMON_VIM_PLUGINS[@]}" "${MYADM_OS_VIM_PLUGINS[@]}"
}


main() {
  source "${MYADM_DIR}"/lib/utils.sh

  case "${OSTYPE}" in 
    "darwin"*)
      source "${MYADM_DIR}"/platform/darwin.sh
      ;;
    "linux-gnu")
      source "${MYADM_DIR}"/platform/linux.sh
      myadm_check_linux
      ;;
    *)
      die "Unsupported platform"
      ;;
  esac

  bootstrap
}


main
