#!/bin/bash

# The goal here is to get yadm installed, clone my dotfile repo, and that's it.  
# Other setup can be done in yadm's bootstrap script (at 
# ~/.config/yadm/bootstrap)

fedora_handler() {
  sudo dnf config-manager -y --add-repo \
    https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_30/home:TheLocehiliosan:yadm.repo
  sudo dnf -y install yadm
}


arch_handler() {
  sudo pacman --noconfirm -Syu --needed base-devel git vim inetutils
  git clone https://aur.archlinux.org/yadm.git
  (cd yadm && makepkg -si --noconfirm)
  rm -rf yadm/
}


# This is for servers where:
# 1. you may not have root access
# 2. extra software is not welcome
centos_handler() {
  [[ ! -d "${HOME}"/.local/bin ]] && mkdir -p "${HOME}"/.local/bin
  
  curl -fLo "${HOME}"/.local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm \
    && chmod a+x "${HOME}"/.local/bin/yadm
}


darwin_handler() {
  /usr/bin/ruby -e "$(
    curl -fsSL \
    https://raw.githubusercontent.com/Homebrew/install/master/install
  )"
  brew install yadm
}


linux_handler() {
  local os="$(grep '^ID=' /etc/os-release | cut -f2 -d"=")"
  os="${os%\"}"
  os="${os#\"}"

  case "${os}" in
    "arch")
      arch_handler
      ;;
    "fedora")
      fedora_handler
      ;;
    "centos")
      centos_handler
      ;;
    *)
      echo "Unsupported OS" >&2
      exit 1
      ;;
  esac
}


main() {
  case "${OSTYPE}" in
    "darwin"*)
      darwin_handler
      ;;
    "linux-gnu")
      linux_handler
      ;;
    *)
      echo "Unsupported platform" >&2
      exit 1
      ;;
  esac

  [[ -f "${HOME}"/.bash_profile ]] && rm -f "${HOME}"/.bash_profile
  [[ -f "${HOME}"/.bashrc ]] && rm -f "${HOME}"/.bashrc
  [[ -f "${HOME}"/.profile ]] && rm -f "${HOME}"/.profile

  yadm clone https://github.com/ironbars/dotfiles.git
}

main
